function FindProxyForURL(_url_, host) {

    var pos, exits = ["DIRECT", "PROXY proxy01.uniontech.com:3128; PROXY proxy02.uniontech.com:3128; PROXY 127.0.0.1:6666; DIRECT", "PROXY 127.0.0.1:6666; DIRECT"];
    var list = {
	"uniontech.com": 0,
	"openai.com": 2,
	"chatgpt.com": 2,
        "apache.org":1,
	"android.com":1,
	"atlassian.com":1,
        "appspot.com":1,
	"adservice.google.com":0,
	"box.com":1,
	"box.net":1,
	"boxcdn.net":1,
	"behance.net":1,
        "brave.com":1,
        "bootstrapcdn.com":1,
	"cloudflare.com":1,
	"chromium.org":1,
        "cdninstagram.com":1,
        "chatdoc.com":1,
        "cnbeta.com.tw":1,
        "cnbetacdn.com":1,
	"deepl.com":1,
        "dropbox.com":1,
        "dropboxstatic.com":1,
       	"dropboxusercontent.com":1,
	"developer.chrome.com":1,
        "discord.com":1,
        "discord.gg":1,
        "distrowatch.com":1,
        "docker.io":1,
        "docker.com":1,
	"ethereum.org":1,
	"facebook.com":1,
	"facebook.net":1,
	"fbcdn.net":1,
        "gcr.io":1,
        "gitlab.com":1,
        "gravatar.com":1,
	"github.com":1,
	"githubassets.com":1,
	"githubusercontent.com":1,
	"google.com":1,
	"google.com.hk":1,
	"googlevideo.com":1,
	"gstatic.com":1,
	"googleapis.com":1,
	"googlesource.com":1,
	"googleusercontent.com":1,
        "godaddy.com":1,
        "huggingface.co":1,
	"intel.com":1,
	"imgur.com":1,
	"instagram.com":1,
        "live.com":1,
        "k8s.io":1,
        "kubernetes.io":1,
        "kubernetes.github.io":1,
        "linkedin.com":1,
        "licdn.com":1,
        "msauth.net":1,
	"medium.com":1,
        "mediawiki.org":1,
        "matrix.org":1,
	"notion.so":1,
        "nvd.nist.gov":1,
        "npmjs.com":1,
        "npmjs.org":1,
        "onenote.com":1,
        "opendev.org":1,
	"openvpn.net":1,
	"pypi.org":1,
        "pinterest.com":1,
        "pinimg.com":1,
        "postman.com":1,
	"quora.com":1,
	"quoracdn.net":1,
        "quay.io":1,
	"redis.io":1,
        "reddit.com":1,
        "redditmedia.com":1,
        "redditstatic.com":1,
	"skia.org":1,
	"sympli.io":1,
	"stackoverflow.com":1,
	"sstatic.net":1,
 	"stackexchange.com":1,
        "security-tracker.debian.org":1,
        "spdx.org":1,
        "t.me":1,
	"telegram.org":1,
	"twitter.com":1,
	"twimg.com":1,
	"transifex.com":1,
        "tu-zi.com":1,
	"wikimedia.org":1,
	"wikipedia.org":1,
	"wordpress.org":1,
        "whatsapp.com":1,
        "whatsapp.net":1,
        "winehq.org":1,
        "x.com":1,
        "youtube.com":1, 
        "ytimg.com":1,
        "yahoo.com":1,
        "zoom.us":1, };
    do {
        if (list.hasOwnProperty(host)) return exits[list[host]];
        pos = host.indexOf(".") + 1;
        host = host.slice(pos)
    } while (pos >= 1)

    return list[2];
}

